/**
 * The web portal builds the ArtTrust domain binding byte-identically to the
 * Python backend (consumers/arttrust/binding.py) and the Dart portal, so a tag
 * minted from the web matches one minted from mobile. Expected values are
 * generated by binding.py.
 */
import test from "node:test";
import assert from "node:assert/strict";

import { arttrustBinding, verdictOf } from "../dist/portal.js";

const toHex = (u8) => [...u8].map((b) => b.toString(16).padStart(2, "0")).join("");

const VECTORS = [
  {
    uid: "04D2760000850100",
    title: "Composition VIII",
    artistId: "artist_0042",
    hex: "b958f7c3cc046a676532abc14aeb0744a394da8c93036bc6950eb010ae1d2600",
  },
  {
    uid: "AABBCCDDEEFF0011",
    title: "Café Terrace",
    artistId: "artist_0099",
    hex: "27aa7e6819afbc4459a3bdcc888f7d9662e2512058f5ff423165de23536e52ac",
  },
];

test("arttrustBinding matches the Python backend", async () => {
  for (const v of VECTORS) {
    assert.equal(toHex(await arttrustBinding(v.uid, v.title, v.artistId)), v.hex);
  }
});

test("verdict policy maps the three booleans", () => {
  const base = { issuer_id: null, reason: "" };
  assert.equal(verdictOf({ ...base, chip_authentic: false, not_replayed: false, issuer_verified: false }), "counterfeit");
  assert.equal(verdictOf({ ...base, chip_authentic: true, not_replayed: false, issuer_verified: false }), "replayed");
  assert.equal(verdictOf({ ...base, chip_authentic: true, not_replayed: true, issuer_verified: false }), "unverified_artist");
  assert.equal(verdictOf({ ...base, chip_authentic: true, not_replayed: true, issuer_verified: true }), "authentic");
});
